version: '3.8'

services:
  kibana:
    image: kibana:7.1.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # 连接到elasticsearch服务
      - TZ=Asia/Shanghai
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - common-app-net

networks:
  common-app-net:
    external: true