version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.34
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - common-app-net

volumes:
  mysql_data:

networks:
  common-app-net:
    external: true
