version: '3.8'

services:
  logstash:
    image: logstash:7.1.1
    container_name: logstash
    hostname: logstash
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9600:9600"   
      - "5044:5044"
    volumes:
      # 挂载配置文件和JDBC驱动
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./conf.d/:/usr/share/logstash/conf.d/
      - ./mysql-connector-j-8.0.31.jar:/usr/share/logstash/logstash-core/lib/jars/mysql-connector-j-8.0.31.jar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - common-app-net


networks:
  common-app-net:
    external: true