version: '3.8'

services:
  redis:
    image: redis:6.2.5
    container_name: redis
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: "123456"  # 设置Redis密码
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]  # 更新健康检查命令
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - common-app-net

volumes:
  redis_data:

networks:
  common-app-net:
    external: true